### ISSUE TITLE
Please consider get rid of the login when app is opened

### ISSUE THREAD

**Issue by SuzukiHonoka** [Lennoard/HEBF#6]
As I always close that activity but it always shown to me.
This is really inconvenient and not good for user experience.
Please consider put it in a optional function.
Thanks!

**Comment by Lennoard** [comment]
Thank you, I agree. What version of the app are you running?

In recent versions, there's an anonymous login, and in the settings screen, you can check "always anonymous" and the login screen will be skipped every time. In the other hand, if you sign in once, the app will remember your credentials and will likely skip the login screen too.

**Comment by SuzukiHonoka** [comment]
The version is 2.3.6
I saw that setting after you told me.
Thanks!
