### ISSUE TITLE
Device crashes when trying to change min/max cpu frequency

### ISSUE THREAD

**Issue by realKarthikNair** [Lennoard/HEBF#9]
Device abruptly reboots if trying to change cpu min/max frequency. 

Device
RMX2193

Kernel
4.14.141+
#1 Sat Dec 12 16:46:27 CST 2020

CPU
MT6763V/CE

OS
Nezuko OS (running on stock kernel and vendor from realme )

> Issue can be reproduced on Lineage os too

**Comment by Lennoard** [comment]
Could you please attach the last kernel message or some logs so that I can have a better direction towards maybe fixing the issue in the app side? This reboot is uncommon behavior.

**Comment by Lennoard** [comment]
I haven't tested that much in MTK CPUs, maybe something is going off really wrong. Here's the relevant code https://github.com/Lennoard/hebf-android/blob/9d7cac9e7f37a65b97012fe6170ccb7365042499/app/src/main/java/com/androidvip/hebf/utils/CpuManager.kt#L122-L129

Maybe you can spot something I didn't know.

**Comment by realKarthikNair** [comment]
Please do tell me if you need anything from /root or something i can help so that you could fix this ASAP

**Comment by Lennoard** [comment]
The contents of the `/sys/devices/system/cpu` dir and some of its subdirs would be welcome
